### PR TITLE
[TASK] Raise allowed php version

### PR DESCRIPTION
**Pull request by tantegerda1**

### CODE REVIEW

**Comment by oliverklee** [comment]
@tantegerda1 You'll need to configure the build matrix in the .travis.yml so that the higher PHP versions are used only for those TYPO3 versions that work with them.

**Comment by tantegerda1** [comment]
@oliverklee Thanks for the hint! I amended the commit, but now Travis/composer fails to get the dev-dependency `namelesscoder/typo3-repository-client`. I'm stuck here.

**Comment by helhum** [comment]
@tantegerda1 I fixed the builds now. can you rebase and force push?

**Comment by tantegerda1** [comment]
gnaaaargh, does not look better now :-(

I assume I rebased it the wrong way? (Did away with the merge and reordered my commit on top.) Can you give me a hint on what to do? Otherways I'm perfectly happy if you ignore my pull request and just commit those small changes in an own commit, if it saves time.

**Comment by helhum** [comment]
just do a `git fetch origin && git rebase -i origin/master` and mark all commits as "squashed" except one, then do a `git push -f` to update your PR (assuming origin points to your fork)

**Comment by tantegerda1** [comment]
Thanks, now I understand what I _should have done_. Since my previous attempt already reordered the commits (mine on top) the editor opened by `rebase -i` would just say `noop`.
Now rebased on `upstream/master` (upstream being your original repository) - which lead me to fix the conflict in `.travis.yml` but I could not squash any commits.
Hope it is correct this way - and thanks a lot for your patience!

**Comment by helhum** [comment]
Cool. Thanks for your contribution!

**Pull request merged**
