### PR TITLE
Update 9.5

### PR DESCRIPTION
**Pull request by vendytjung**
@helhum we try to use middleware to handle it, can you please check this pull request?

### CODE REVIEW

**Comment by helhum** [comment]
@vendytjung awesome, thanks. Looks very good already. I will take care to remove TYPO3 6.2 and PHP 5 compatibility to ease the further development. I will also add the tests for 9.5 and see if your implementation works (with the tests)

Does it work for you in general? Did you do some tests or is it in use?

**Comment by vendytjung** [comment]
@helhum in general it work for me :) we use it our actual project.

**Comment by vendytjung** [comment]
i am agree with you, for TYPO3 8.7 we can still use Version 2.1.0

**Comment by vendytjung** [comment]
I see that you have already checked the code and make optimize, thanks.

**Comment by helhum** [comment]
I pushed some commits, but I did not merge yet :)

**Pull request merged**
