### PR TITLE
[BUGFIX] Adjust widget view helpers to use new API

### PR DESCRIPTION
**Pull request by helhum**
Closes: #62
Closes: #64

### CODE REVIEW

**Comment by helhum** [comment]
@nigelmann @DaRealFreak can you check if this implementation would fix your issues with widget VHs? Thanks!

**Comment by DaRealFreak** [comment]
Not quite for me.
The ViewHelper doesn't accept the contextRecord argument (and extensionName, pluginName, argumentsToBeExcludedFromQueryString) contrary to the normal UriViewHelper which causes the error:
```Argument 3 passed to Helhum\TyposcriptRendering\Uri\TyposcriptRenderingUri::buildTypoScriptRenderingConfiguration() must be of the type string, null given, called in /var/www/html/webroot/web/typo3conf/ext/typoscript_rendering/Classes/Uri/TyposcriptRenderingUri.php on line 70```

Adding the missing arguments to the ViewHelper generates a valid but wrong URI:
```https://t9.test/?tx_test_p1[controller]=ViewHelpers\Widget\AjaxPaginate&tx_test_p1[currentPage]=2&tx_typoscriptrendering[context]={%22record%22%3A%22tt_content_2497%22%2C%22path%22%3A%22tt_content.list.20.test_p1%22}&cHash=becf0594107693f876325e7d40083e08```

It is using the ControllerContext of the Widget Controller.
Checking the instance of the request would solve this.
For example the extension name:
```
$request = $renderingContext->getControllerContext()->getRequest();
if ($request instanceof WidgetRequest) {
    $extensionName = $request->getWidgetContext()->getParentExtensionName();
} else {
    $extensionName = $request->getControllerExtensionName();
}
```

**Comment by DaRealFreak** [comment]
Okay.
The uriFor action is also adding the controller/action of the Paginate Controller if it's not identical to the action/controller of the content element I want to render. The core Widget ViewHelper is using the build function on the uriBuilder too.
So in total I needed these changes to get it to work properly.

```
diff --git a/Classes/Uri/TyposcriptRenderingUri.php b/Classes/Uri/TyposcriptRenderingUri.php
index c9d5ed9..b247ce7 100644
--- a/Classes/Uri/TyposcriptRenderingUri.php
+++ b/Classes/Uri/TyposcriptRenderingUri.php
@@ -18,6 +18,7 @@ use Helhum\TyposcriptRendering\Configuration\ConfigurationBuildingException;
 use Helhum\TyposcriptRendering\Configuration\RecordRenderingConfigurationBuilder;
 use Helhum\TyposcriptRendering\Renderer\RenderingContext;
 use TYPO3\CMS\Core\Http\Uri;
+use TYPO3\CMS\Fluid\Core\Widget\WidgetRequest;
 
 class TyposcriptRenderingUri extends Uri
 {
@@ -39,6 +40,7 @@ class TyposcriptRenderingUri extends Uri
     {
         $arguments = $viewHelperContext->getArguments();
         $controllerContext = $viewHelperContext->getControllerContext();
+        $request = $controllerContext->getRequest();
 
         $pluginName = $arguments['pluginName'] ?? null;
         $extensionName = $arguments['extensionName'] ?? null;
@@ -49,10 +51,18 @@ class TyposcriptRenderingUri extends Uri
         $addTypoScriptRenderingArguments = $arguments['addTypoScriptRenderingArguments'] ?? true;
 
         if ($pluginName === null) {
-            $pluginName = $controllerContext->getRequest()->getPluginName();
+            if ($request instanceof WidgetRequest) {
+                $pluginName = $request->getWidgetContext()->getParentPluginName();
+            } else {
+                $pluginName = $controllerContext->getRequest()->getPluginName();
+            }
         }
         if ($extensionName === null) {
-            $extensionName = $controllerContext->getRequest()->getControllerExtensionName();
+            if ($request instanceof WidgetRequest) {
+                $extensionName = $request->getWidgetContext()->getParentExtensionName();
+            } else {
+                $extensionName = $controllerContext->getRequest()->getControllerExtensionName();
+            }
         }
         if ($contextRecord === 'current') {
             if (
@@ -73,6 +83,12 @@ class TyposcriptRenderingUri extends Uri
             $additionalParams['tx_typoscriptrendering']['context'] = json_encode($renderingConfiguration);
         }
 
+        if ($request instanceof WidgetRequest) {
+            // adding the widget prefix for the arguments, use them together with the additionalParams
+            $additionalParams[$request->getArgumentPrefix()] = $arguments['arguments'];
+            unset($arguments['arguments']);
+        }
+
         $uriBuilder = $controllerContext->getUriBuilder();
         $uriBuilder->reset()
             ->setTargetPageUid($arguments['pageUid'])
@@ -86,14 +102,22 @@ class TyposcriptRenderingUri extends Uri
             ->setAddQueryStringMethod($arguments['addQueryStringMethod'])
             ->setArgumentsToBeExcludedFromQueryString($arguments['argumentsToBeExcludedFromQueryString']);
 
-        $this->parseUri(
-            $uriBuilder->uriFor(
+        if ($request instanceof WidgetRequest) {
+            // uriFor only checks for the default controller/action of the current request context
+            // not the widget context, so using build here prevents the widget controller from being added to the URI
+            $uri = $uriBuilder->build();
+        } else {
+            $uri = $uriBuilder->uriFor(
                 $arguments['action'] ?? null,
                 $arguments['arguments'] ?? null,
                 $arguments['controller'] ?? null,
                 $extensionName,
                 $pluginName
-            ),
+            );
+        }
+
+        $this->parseUri(
+            $uri,
             $renderingPath !== null
         );
     }
diff --git a/Classes/ViewHelpers/Widget/LinkViewHelper.php b/Classes/ViewHelpers/Widget/LinkViewHelper.php
index f0af3a8..d7eb102 100644
--- a/Classes/ViewHelpers/Widget/LinkViewHelper.php
+++ b/Classes/ViewHelpers/Widget/LinkViewHelper.php
@@ -48,6 +48,11 @@ class LinkViewHelper extends AbstractTagBasedViewHelper
         $this->registerArgument('section', 'string', 'The anchor to be added to the URI', false, '');
         $this->registerArgument('format', 'string', 'The requested format, e.g. ".html', false, '');
         $this->registerArgument('ajax', 'bool', 'TRUE if the URI should be to an AJAX widget, FALSE otherwise.', false, true);
+
+        $this->registerArgument('extensionName', 'string', 'Target Extension Name (without "tx_" prefix and no underscores). If NULL the current extension name is used');
+        $this->registerArgument('pluginName', 'string', 'Target plugin. If empty, the current plugin name is used');
+        $this->registerArgument('contextRecord', 'string', 'The record that the rendering should depend upon. e.g. current (default: record is fetched from current Extbase plugin), tt_content:12 (tt_content record with uid 12), pages:15 (pages record with uid 15), \'currentPage\' record of current page', false, 'current');
+        $this->registerArgument('argumentsToBeExcludedFromQueryString', 'array', 'arguments to be removed from the URI. Only active if $addQueryString = TRUE', false, []);
     }
 
     /**
diff --git a/Classes/ViewHelpers/Widget/UriViewHelper.php b/Classes/ViewHelpers/Widget/UriViewHelper.php
index 13020e5..5ffb63f 100644
--- a/Classes/ViewHelpers/Widget/UriViewHelper.php
+++ b/Classes/ViewHelpers/Widget/UriViewHelper.php
@@ -37,6 +37,11 @@ class UriViewHelper extends AbstractViewHelper
         $this->registerArgument('section', 'string', 'The anchor to be added to the URI', false, '');
         $this->registerArgument('format', 'string', 'The requested format, e.g. ".html', false, '');
         $this->registerArgument('ajax', 'bool', 'TRUE if the URI should be to an AJAX widget, FALSE otherwise.', false, true);
+
+        $this->registerArgument('extensionName', 'string', 'Target Extension Name (without "tx_" prefix and no underscores). If NULL the current extension name is used');
+        $this->registerArgument('pluginName', 'string', 'Target plugin. If empty, the current plugin name is used');
+        $this->registerArgument('contextRecord', 'string', 'The record that the rendering should depend upon. e.g. current (default: record is fetched from current Extbase plugin), tt_content:12 (tt_content record with uid 12), pages:15 (pages record with uid 15), \'currentPage\' record of current page', false, 'current');
+        $this->registerArgument('argumentsToBeExcludedFromQueryString', 'array', 'arguments to be removed from the URI. Only active if $addQueryString = TRUE', false, []);
     }
 
     /**

```

**Comment by helhum** [comment]
> In total I needed these changes to get it to fully work properly.

Thanks a bunch for your test and the patch!

**Pull request merged**
